#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12

PROBE_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$PROBE_DIR"
ENV_FILE="$PROBE_DIR/.wizard.env"
APP="$PROBE_DIR/dist/Recap TCC Probe.app"
BUNDLE_ID="com.qodesmith.recap.tcc-probe"
RESULTS="$PROBE_DIR/results.md"

record()  { printf '%s\n' "$1" >> "$RESULTS"; }
heading() { { echo; echo "## $1"; echo; } >> "$RESULTS"; }
record_build() {
  codesign -dvv "$APP" 2>&1 \
    | grep -E '^(Identifier|TeamIdentifier|Authority|Signature|CDHash)' \
    | sed 's/^/    /' >> "$RESULTS" || true
}
reset_tcc() {
  if tccutil reset All "$BUNDLE_ID" >/dev/null 2>&1; then
    say "✓ TCC reset for $BUNDLE_ID (clean slate)"
  else
    warn "tccutil reset failed — remove '$BUNDLE_ID' entries by hand in System Settings"
  fi
}

banner "Recap #27 — does a signed .app get the system-audio prompt, and does the grant survive a rebuild?"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Preflight"
say "This wizard measures how macOS TCC treats the system-audio tap for a real"
say ".app bundle, across three signing identities: ad-hoc, self-signed, and a"
say "free Apple Development certificate. Your observations land in results.md."
echo
warn "During EVERY tap probe, keep music playing (Music, YouTube, anything)."
warn "A silent system is indistinguishable from a denied tap — that fact is"
warn "half of what this map's meters exist for."
echo
command -v swift >/dev/null 2>&1 || { warn "swift not found — install Xcode CLT first"; exit 1; }
{ echo; echo "# TCC probe run — $(date)"; echo; sw_vers | sed 's/^/    /'; } >> "$RESULTS"
say "Results file: $RESULTS"
note "The app also writes everything to ~/Library/Logs/RecapTCCProbe.log"
pause

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Build ad-hoc + clean slate"
say "Building the probe app with an ad-hoc signature (codesign -s -)…"
./build.sh adhoc
reset_tcc
heading "Phase A — ad-hoc signature"
record "Build 1 (ad-hoc):"
record_build
echo
note "Ad-hoc = no certificate. Apple DTS says TCC's handle on such a program"
note "changes on every rebuild — that's what Phase A verifies for audio taps."
pause

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Ad-hoc first launch — does the prompt fire? (measurement 1)"
step "Start your music now."
say "Launching the app (via LaunchServices — same attribution as a double-click):"
open "$APP"
step "In the app, click '1 · System tap — in-process'. The tap is created the"
step "moment you click — if the system-audio prompt is going to auto-fire, it"
step "fires now."
step "Watch for: a macOS prompt naming 'Recap TCC Probe' and showing OUR purpose"
step "string ('…captures system audio to verify…'). If it appears, click Allow."
note "The first probe will likely end in SILENCE because you granted mid-probe."
note "That's expected — the next stage measures post-grant behaviour."
ask M1_PROMPT "Did the prompt auto-fire, named correctly, with our string? (describe):"
record "- M1 · prompt on first tap IO (ad-hoc bundle): $M1_PROMPT"
ask M1_FIRST "Verdict line of that first probe (SIGNAL/SILENCE/ERROR):"
record "- M1 · first-probe verdict (grant arrived mid-probe): $M1_FIRST"

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Post-grant, same process — is a relaunch required? (measurement 3)"
step "WITHOUT quitting the app, music still playing, click button 1 again."
ask M3_SAME "Verdict now (SIGNAL/SILENCE/ERROR):"
record "- M3 · post-grant, same process, no relaunch: $M3_SAME"
case "$M3_SAME" in
  *SIL*|*sil*|*Sil*)
    warn "Silence post-grant — now measure whether a relaunch fixes it."
    step "Quit the app (⌘Q), then press Enter — I'll relaunch it."
    pause
    open "$APP"
    step "Music playing; click button 1 again."
    ask M3_RELAUNCH "Verdict after relaunch (SIGNAL/SILENCE/ERROR):"
    record "- M3 · after relaunch: $M3_RELAUNCH"
    ;;
  *)
    record "- M3 · relaunch not needed (signal without restarting the app)"
    say "✓ No relaunch needed — recorded."
    ;;
esac

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "System Settings — listed by name? (measurement 2)"
open_url "x-apple.systempreferences:com.apple.preference.security?Privacy_ScreenCapture"
step "If that didn't land there: System Settings → Privacy & Security →"
step "Screen & System Audio Recording."
step "Look for 'Recap TCC Probe' — note WHICH section (System Audio Recording"
step "Only vs Screen & System Audio) and whether its toggle is on."
ask M2 "Listed by name? Which section? Toggle state?:"
record "- M2 · Privacy-pane entry (ad-hoc): $M2"

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Child process — the sidecar shape (measurement 7)"
say "Recap ships capture behind a sidecar (#7), so the grant must cover child"
say "processes of the bundle."
step "Music playing; in the app click '2 · System tap — child process'."
step "Watch for any NEW prompt (there should be none) and check the Privacy"
step "pane afterwards for any NEW entry (e.g. 'recap-probe-helper')."
ask M7 "Child verdict + any new prompt or Settings entry?:"
record "- M7 · child-process (sidecar) attribution: $M7"

# ── Stage 7 ───────────────────────────────────────────────────────────────
stage "Microphone from a bundle (measurement 6)"
step "Click '3 · Mic — preflight status'. It must print a status WITHOUT any"
step "prompt appearing."
ask M6_PRE "Status shown, and did clicking 3 fire a prompt? (should not):"
record "- M6 · mic preflight without prompt: $M6_PRE"
step "Click '4 · Mic — request + capture 3 s'. The mic prompt should fire; click"
step "Allow, then say something."
ask M6_REQ "Mic verdict (SIGNAL with no relaunch?):"
record "- M6 · mic grant → capture, same process: $M6_REQ"

# ── Stage 8 ───────────────────────────────────────────────────────────────
stage "Ad-hoc rebuild — does the grant survive? (measurements 4a + 5)"
say "This is the Apple-DTS claim and the Cap failure mode, for audio taps."
step "Quit the app (⌘Q), then press Enter — I'll rebuild with a fresh CDHash."
pause
./build.sh adhoc
record "Build 2 (ad-hoc, rebuilt — note the changed CDHash):"
record_build
open "$APP"
step "Music playing; click button 1. Do NOT touch System Settings first."
step "Three things can happen: a fresh prompt (grant lost, honestly), SIGNAL"
step "(grant survived), or SILENCE with no prompt (the Cap silent rejection)."
ask M4A "What happened? (prompt? verdict?):"
record "- M4a · ad-hoc rebuild, same grant: $M4A"
step "Now check the Privacy pane: one entry or two? Toggle still on?"
ask M4A_SET "Privacy-pane state after rebuild:"
record "- M4a · Privacy pane after ad-hoc rebuild: $M4A_SET"

# ── Stage 9 ───────────────────────────────────────────────────────────────
stage "Optional: self-signed certificate (stable identity, NO Team ID)"
say "Extra evidence beyond the ticket's two identities: a self-signed cert is"
say "stable across rebuilds but has no Apple Team ID. If Cap's rejection is a"
say "Team-ID gate, this fails like ad-hoc; if it's only about stability, this"
say "survives rebuilds. ~3 minutes, no Xcode needed."
if confirm "Run the self-signed arm?"; then
  if ! security find-identity -v -p codesigning 2>/dev/null | grep -q "Recap Probe Signing"; then
    step "Open Keychain Access (I'll launch it):"
    open -a "Keychain Access" || true
    step "Menu bar: Keychain Access → Certificate Assistant → Create a Certificate…"
    step "  Name: Recap Probe Signing"
    step "  Identity Type: Self-Signed Root"
    step "  Certificate Type: Code Signing"
    step "Click Create, then Done."
    pause "Press Enter when the certificate exists."
  fi
  if security find-identity -v -p codesigning 2>/dev/null | grep -q "Recap Probe Signing"; then
    ./build.sh selfsigned
    note "If a keychain dialog asks to let codesign use the key: Always Allow."
    reset_tcc
    heading "Phase B — self-signed certificate (stable identity, no Team ID)"
    record "Build 1 (self-signed):"
    record_build
    open "$APP"
    step "Music playing; click button 1; Allow the prompt; click button 1 again."
    ask SS_FIRST "First run: prompt fired? second probe verdict?:"
    record "- Self-signed first run: $SS_FIRST"
    step "Quit the app (⌘Q), then press Enter — rebuilding with the same cert."
    pause
    ./build.sh selfsigned
    record "Build 2 (self-signed, rebuilt):"
    record_build
    open "$APP"
    step "Music playing; click button 1. Prompt again, signal, or silence?"
    ask SS_REBUILD "Rebuild: prompt? verdict?:"
    record "- Self-signed rebuild, same grant: $SS_REBUILD"
  else
    warn "Certificate 'Recap Probe Signing' not found — skipping this arm."
    record "- Self-signed arm: SKIPPED (certificate not created)"
  fi
else
  record "- Self-signed arm: SKIPPED by choice"
fi

# ── Stage 10 ──────────────────────────────────────────────────────────────
stage "Free Apple Development certificate — create it"
say "The identity #26 chose: free Apple ID, no \$99 membership. Creating it"
say "requires Xcode (the full app, not just the command-line tools)."
if security find-identity -v -p codesigning 2>/dev/null | grep -q "Apple Development"; then
  say "✓ An 'Apple Development' identity already exists — nothing to create."
else
  if ! ls -d /Applications/Xcode*.app >/dev/null 2>&1; then
    warn "Xcode is not installed. It is a large download (~10 GB) — install it"
    warn "from the App Store, launch it once, and agree to the license."
    open_url "https://apps.apple.com/app/xcode/id497799835"
  fi
  step "In Xcode: Xcode → Settings… → Accounts → '+' → Apple ID → sign in."
  step "Select your Personal Team → 'Manage Certificates…' → '+' →"
  step "'Apple Development'."
  pause "Press Enter once the certificate exists (or Ctrl-C to stop here and resume later — re-running the wizard is safe)."
  if ! security find-identity -v -p codesigning 2>/dev/null | grep -q "Apple Development"; then
    warn "Still no 'Apple Development' identity. Stages 11 will be skipped —"
    warn "re-run the wizard when the certificate exists."
  fi
fi

# ── Stage 11 ──────────────────────────────────────────────────────────────
stage "Dev-signed: first run, then the rebuild that matters (measurement 4b)"
if security find-identity -v -p codesigning 2>/dev/null | grep -q "Apple Development"; then
  ./build.sh dev
  reset_tcc
  heading "Phase C — free Apple Development certificate"
  record "Build 1 (dev):"
  record_build
  open "$APP"
  step "Music playing; click button 1; Allow the prompt; click button 1 again."
  ask DEV_FIRST "First run: prompt fired with our string? second probe verdict?:"
  record "- Dev-signed first run: $DEV_FIRST"
  step "Check the Privacy pane: entry name + section?"
  ask DEV_SET "Privacy-pane entry (dev-signed):"
  record "- Dev-signed Privacy-pane entry: $DEV_SET"
  step "Quit the app (⌘Q), then press Enter — rebuilding: same identity, new CDHash."
  pause
  ./build.sh dev
  record "Build 2 (dev, rebuilt — same Team ID, new CDHash):"
  record_build
  open "$APP"
  step "Music playing; click button 1. Do NOT touch System Settings first."
  step "SIGNAL with no new prompt = the grant survived the rebuild — the result"
  step "#26's whole signing decision is waiting on."
  ask DEV_REBUILD "Rebuild: prompt? verdict?:"
  record "- M4b · dev-signed rebuild, same grant: $DEV_REBUILD"
else
  warn "No 'Apple Development' identity — skipping the dev-signed arm."
  record "- Dev-signed arm: SKIPPED (no Apple Development identity)"
  SKIPPED+=("Dev-signed arm — create the free certificate and re-run the wizard")
fi

# ── Stage 12 ──────────────────────────────────────────────────────────────
stage "Wrap up"
say "All observations are in:"
say "  $RESULTS"
note "App log (verdict lines, signing info per launch): ~/Library/Logs/RecapTCCProbe.log"
step "Hand results.md back to the wayfinder session so it can resolve ticket #27"
step "— or paste it as a comment on the issue."
say "Cleanup when done for good: delete the 'Recap TCC Probe' entries in the"
say "Privacy pane (or 'tccutil reset All $BUNDLE_ID'), and delete the"
say "'Recap Probe Signing' certificate in Keychain Access if you created it."
pause

finish
